main: me.prouser123.essentialtools.Main
name: EssentialTools
version: 1.0
author: Prouser123
description: A collection of tools.
commands:
  etools:
    description: A test command
    usage: /etools <arguments> | This command may be disabled.
    permission: etools.use
    permission-message: No permissions!
  admin:
    description: Admin GUI
    usage: /admin | This command may be disabled.
    permission: etools.gui.admin
    permission-message: No permissions!
  menu:
    description: Public GUI
    usage: /menu | This command may be disabled
    permission: etools.gui.public
    permission-message: No permissions!
  nv:
    description: Enable or Disable Night Vision
    usage: /nv | This command may be disabled.
    permission: etools.nv
    permission-message: No permissions!